2013/04/24 13:28:24 [error] [php] mail() [<a href='function.mail'>function.mail</a>]: Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() (C:\xampp\htdocs\ActiRepCORE\protected\controllers\SiteController.php:67)
Stack trace:
#0 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CController.php(308): CInlineAction->runWithParams()
#1 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CController.php(286): SiteController->runAction()
#2 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CController.php(265): SiteController->runActionWithFilters()
#3 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CWebApplication.php(282): SiteController->run()
#4 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CWebApplication.php(141): CWebApplication->runController()
#5 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\base\CApplication.php(169): CWebApplication->processRequest()
#6 C:\xampp\htdocs\ActiRepCORE\index.php(13): CWebApplication->run()
REQUEST_URI=/ActiRepCORE/index.php?r=site/contact
in C:\xampp\htdocs\ActiRepCORE\protected\controllers\SiteController.php (67)
in C:\xampp\htdocs\ActiRepCORE\index.php (13)
2013/04/24 13:39:19 [error] [php] mail() [<a href='function.mail'>function.mail</a>]: Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() (C:\xampp\htdocs\ActiRepCORE\protected\controllers\SiteController.php:67)
Stack trace:
#0 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CController.php(308): CInlineAction->runWithParams()
#1 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CController.php(286): SiteController->runAction()
#2 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CController.php(265): SiteController->runActionWithFilters()
#3 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CWebApplication.php(282): SiteController->run()
#4 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CWebApplication.php(141): CWebApplication->runController()
#5 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\base\CApplication.php(169): CWebApplication->processRequest()
#6 C:\xampp\htdocs\ActiRepCORE\index.php(13): CWebApplication->run()
REQUEST_URI=/ActiRepCORE/index.php?r=site/contact
in C:\xampp\htdocs\ActiRepCORE\protected\controllers\SiteController.php (67)
in C:\xampp\htdocs\ActiRepCORE\index.php (13)
2013/04/24 15:10:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\ActiRepCORE\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/ActiRepCORE/index.php?r=gii
---
2013/04/25 10:56:21 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\db\CDbConnection.php:381
Stack trace:
#0 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\gii\generators\model\ModelCode.php(57): CModule->__get('db')
#5 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CWebApplication.php(282): CController->run('')
#13 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model')
#14 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\base\CApplication.php(169): CWebApplication->processRequest()
#15 C:\xampp\htdocs\ActiRepCORE\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/ActiRepCORE/index.php/gii/model
HTTP_REFERER=http://localhost/ActiRepCORE/index.php/gii/default/index
---
2013/04/25 10:57:54 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\db\CDbConnection.php:381
Stack trace:
#0 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\gii\generators\model\ModelCode.php(57): CModule->__get('db')
#5 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CWebApplication.php(282): CController->run('')
#13 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model')
#14 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\base\CApplication.php(169): CWebApplication->processRequest()
#15 C:\xampp\htdocs\ActiRepCORE\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/ActiRepCORE/index.php/gii/model
HTTP_REFERER=http://localhost/ActiRepCORE/index.php/gii/default/index
---
2013/04/25 10:58:03 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\db\CDbConnection.php:381
Stack trace:
#0 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\gii\generators\model\ModelCode.php(57): CModule->__get('db')
#5 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CWebApplication.php(282): CController->run('')
#13 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model')
#14 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\base\CApplication.php(169): CWebApplication->processRequest()
#15 C:\xampp\htdocs\ActiRepCORE\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/ActiRepCORE/index.php/gii/model
HTTP_REFERER=http://localhost/ActiRepCORE/index.php/gii/default/index
---
2013/04/25 11:09:27 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\db\CDbConnection.php:381
Stack trace:
#0 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\gii\generators\model\ModelCode.php(57): CModule->__get('db')
#5 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CWebApplication.php(282): CController->run('')
#13 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model')
#14 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\base\CApplication.php(169): CWebApplication->processRequest()
#15 C:\xampp\htdocs\ActiRepCORE\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/ActiRepCORE/index.php/gii/model
HTTP_REFERER=http://localhost/ActiRepCORE/index.php/gii
---
2013/04/25 11:36:44 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'dev-root'@'localhost' (using password: YES)' in C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\db\CDbConnection.php:381
Stack trace:
#0 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\gii\generators\model\ModelCode.php(57): CModule->__get('db')
#5 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CWebApplication.php(282): CController->run('')
#13 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model')
#14 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\base\CApplication.php(169): CWebApplication->processRequest()
#15 C:\xampp\htdocs\ActiRepCORE\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/ActiRepCORE/index.php/gii/model
HTTP_REFERER=http://localhost/ActiRepCORE/index.php/gii
---
2013/04/25 11:42:12 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\gii\GiiModule.php:168
Stack trace:
#0 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CWebApplication.php(282): CController->run('')
#2 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#3 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\ActiRepCORE\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/ACTIREPCORE/index.php/gii
---
2013/04/25 11:43:17 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\gii\GiiModule.php:168
Stack trace:
#0 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CWebApplication.php(282): CController->run('')
#2 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#3 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\ActiRepCORE\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/ACTIREPCORE/index.php/gii
---
2013/04/25 11:54:05 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'actirepcore.usuarios' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `Usuarios`.
in C:\xampp\htdocs\ActiRepCORE\index.php (13)
2013/04/25 13:18:53 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO `tb_tipo_entregable` (`ID_TIPO_ENTREGABLE`, `REFERENCIA`, `DESCRIPCION`) VALUES (:yp0, :yp1, :yp2).
in C:\xampp\htdocs\ActiRepCORE\protected\controllers\TbTipoEntregableController.php (73)
in C:\xampp\htdocs\ActiRepCORE\index.php (13)
2013/04/25 13:18:53 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO `tb_tipo_entregable` (`ID_TIPO_ENTREGABLE`, `REFERENCIA`, `DESCRIPCION`) VALUES (:yp0, :yp1, :yp2)' in C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\db\CDbCommand.php:357
Stack trace:
#0 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\db\ar\CActiveRecord.php(1023): CDbCommand->execute()
#1 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\db\ar\CActiveRecord.php(795): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\ActiRepCORE\protected\controllers\TbTipoEntregableController.php(73): CActiveRecord->save()
#3 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\actions\CInlineAction.php(49): TbTipoEntregableController->actionCreate()
#4 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CController.php(291): CFilterChain->run()
#11 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\web\CWebApplication.php(141): CWebApplication->runController('tbtipoentregabl...')
#14 C:\PHP Frameworks\yii-1.1.13.e9e4a0\framework\base\CApplication.php(169): CWebApplication->processRequest()
#15 C:\xampp\htdocs\ActiRepCORE\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/actirepcore/index.php/tbtipoentregable/create
HTTP_REFERER=http://jlambert/actirepcore/index.php/tbtipoentregable/create
---
